title: Nothing new on the horizon
author:
  name: Martin Jalaf
  email: your-email@domain.com
description: >-
  This is just another site to help me to store some memories and technical
  stuff.
baseurl: /
url: 'https://mjalaf.github.io/'
twitter_username: mjalaf
github_username: mjalaf
markdown: kramdown
disqus:
  shortname: mjalaf
theme: minima
minima:
  skin: classic
  social_links:
    twitter: mjalaf
    github: mjalaf
    linkedin: mjalaf
plugins:
  - jekyll-feed
