title: Martin Jalaf
author:
  name: 'To get a hold of me, you can email me at'
  email: infodredgo@gmail.com
description: Helping people and companies to get better result with technologies.
show_excerpts: false
baseurl: ''
url: 'https://mjalaf.github.io'
disqus:
  shortname: mjalaf
markdown: kramdown
minima:
  date_format: '%b %-d, %Y'
  skin: dark
  social_links:
    twitter: mjalaf
    github: mjalaf
    500px: mjalaf
    rss: true
plugins:
  - jekyll-feeds
  - jekyll-seo-tag
